Repository datastax/adelphi, pull requests merged in 2020-12, with the labels that each got.

#63 33 a little metadata
  python/adelphi/adelphi/cql.py
  python/adelphi/adelphi/gemini.py
  python/adelphi/bin/adelphi
  python/adelphi/setup.py
Labels: easy

#54 #3 UDT support / Overall Unit & Integration tests
  .gitignore
  helm/adelphi/templates/cassandra-clusters.yaml
  helm/adelphi/templates/cassandra-image-builder.yaml
  helm/adelphi/templates/workflow-adelphi.yaml
  helm/adelphi/values.yaml
  python/adelphi/adelphi/anonymize.py
  python/adelphi/adelphi/cql.py
  python/adelphi/adelphi/store.py
  python/adelphi/bin/adelphi
  python/adelphi/integration-tests/adelphi-docker-tests.sh
  python/adelphi/integration-tests/base-schema.cql
  python/adelphi/integration-tests/schemas/2.1.22.cql
  python/adelphi/integration-tests/schemas/2.2.19.cql
  python/adelphi/integration-tests/schemas/3.0.23.cql
  python/adelphi/integration-tests/schemas/3.11.9.cql
  python/adelphi/integration-tests/schemas/4.0-beta3.cql
  python/adelphi/tests/unit/schema_util.py
  python/adelphi/tests/unit/test_anonymize.py
Labels: hard

#75 #48 PyPI publishing
  python/adelphi/README.md
  python/adelphi/bin/adelphi
  python/adelphi/setup.py
Labels: medium

#71 #67 Fix for naming collisions + Python2 support for create_fork + other minor fixes
  python/adelphi/README.md
  python/adelphi/adelphi/cql.py
  python/adelphi/adelphi/gemini.py
  python/adelphi/adelphi/gh.py
  python/adelphi/bin/adelphi
  python/adelphi/setup.py
Labels: medium

#78 #74 Metadata reform
  python/adelphi/adelphi/__init__.py
  python/adelphi/adelphi/cql.py
  python/adelphi/adelphi/export.py
  python/adelphi/adelphi/gemini.py
  python/adelphi/adelphi/gh.py
  python/adelphi/bin/adelphi
  python/adelphi/integration-tests/adelphi-docker-tests.sh
  python/adelphi/integration-tests/schemas/2.1.22.cql
  python/adelphi/integration-tests/schemas/2.2.19.cql
  python/adelphi/integration-tests/schemas/3.0.23.cql
  python/adelphi/integration-tests/schemas/3.11.9.cql
  python/adelphi/integration-tests/schemas/4.0-beta3.cql
Labels: medium
