Repository datastax/adelphi, pull requests merged in 2021-02, with the labels that each got.

#97 Updates to README
  GETTING_STARTED.md
  README.md
Labels: documentation, easy

#90 #46 Grafana dashboard
  helm/adelphi/config/grafana/nb4-new-dashboard.json
  helm/adelphi/templates/grafana-configmap.yaml
  helm/adelphi/templates/grafana-service.yaml
  helm/adelphi/templates/grafana.yaml
  helm/adelphi/templates/graphite-configmap.yaml
  helm/adelphi/templates/graphite-service.yaml
  helm/adelphi/templates/graphite.yaml
  helm/adelphi/templates/nosqlbench-jobs.yaml
  helm/adelphi/templates/prometheus-configmap.yaml
  helm/adelphi/templates/prometheus-service.yaml
  helm/adelphi/templates/prometheus.yaml
  helm/adelphi/values.yaml
Labels: medium

#96 #86 Base support for nb.yaml generation
  python/adelphi/adelphi/__init__.py
  python/adelphi/adelphi/exceptions.py
  python/adelphi/adelphi/export.py
  python/adelphi/adelphi/gemini.py
  python/adelphi/adelphi/nb.py
  python/adelphi/bin/adelphi
  python/adelphi/setup.py
Labels: hard
